<a href="https://colab.research.google.com/github/2303A52359/Generative-AI/blob/main/2303A52359_week8_ASS8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, classification_report


In [2]:

data = pd.read_csv("/content/winequality-red (1).csv")  # Update with actual path if needed

In [3]:
X = data.drop("quality", axis=1)
y = data["quality"]


In [4]:
y = pd.cut(y, bins=[0, 5, 6, 10], labels=[0, 1, 2])  # Adjust for classification

In [5]:
y = pd.get_dummies(y)  # One-hot encoding for ANN classification

In [6]:

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [7]:

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


In [8]:

model = keras.Sequential([
    keras.layers.Dense(16, activation='relu', input_shape=(X_train.shape[1],)),
    keras.layers.Dense(20, activation='relu'),
    keras.layers.Dense(25, activation='relu'),
    keras.layers.Dense(10, activation='relu'),
    keras.layers.Dense(y.shape[1], activation='softmax')  # Output layer
])

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [9]:
model.compile(optimizer='adadelta', loss='categorical_crossentropy', metrics=['accuracy'])

In [10]:
history = model.fit(X_train, y_train, epochs=100, batch_size=64, validation_data=(X_test, y_test))

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 4s 51ms/step - accuracy: 0.1846 - loss: 1.1493 - val_accuracy: 0.2062 - val_loss: 1.1522
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.1770 - loss: 1.1555 - val_accuracy: 0.2062 - val_loss: 1.1520
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - accuracy: 0.1993 - loss: 1.1450 - val_accuracy: 0.2062 - val_loss: 1.1518
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - accuracy: 0.1977 - loss: 1.1396 - val_accuracy: 0.2062 - val_loss: 1.1516
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - accuracy: 0.2017 - loss: 1.1398 - val_accuracy: 0.2062 - val_loss: 1.1514
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.2125 - loss: 1.1475 - val_accuracy: 0.2062 - val_loss: 1.1512
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.1875 - loss: 1.1472 - val_accuracy: 0.2125 - val_loss: 1.1510
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.2003 - loss: 1.1454 - val_accuracy: 0.

In [11]:

loss, accuracy = model.evaluate(X_test, y_test)
print(f"Test Accuracy: {accuracy}")

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2975 - loss: 1.1270  
Test Accuracy: 0.2874999940395355


In [12]:

y_pred = model.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)
y_true = np.argmax(y_test.values, axis=1)

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step 


In [13]:

conf_matrix = confusion_matrix(y_true, y_pred_classes)
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", classification_report(y_true, y_pred_classes))

Confusion Matrix:
 [[57  2 82]
 [51  6 75]
 [16  2 29]]
Classification Report:
               precision    recall  f1-score   support

           0       0.46      0.40      0.43       141
           1       0.60      0.05      0.08       132
           2       0.16      0.62      0.25        47

    accuracy                           0.29       320
   macro avg       0.41      0.36      0.25       320
weighted avg       0.47      0.29      0.26       320



In [14]:

model.save("wine_quality_model.h5")

In [15]:

def load_model():
    loaded_model = keras.models.load_model("wine_quality_model.h5")
    return loaded_model


In [16]:

loaded_model = load_model()
predictions = loaded_model.predict(X_test[:5])
print("Sample Predictions:", np.argmax(predictions, axis=1))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 227ms/step
Sample Predictions: [0 2 2 2 2]
